#include "AppResourceId.h"
/* IDL_FORM_ACHIEVEMENT */
const wchar_t* IDL_FORM_ACHIEVEMENT = L"IDL_FORM_ACHIEVEMENT";
const wchar_t* IDC_ACHIEVEMENT_SCROLLPANEL = L"IDC_ACHIEVEMENT_SCROLLPANEL";
const wchar_t* IDC_ACHIEVEMENT_LABEL_TITLE = L"IDC_ACHIEVEMENT_LABEL_TITLE";
/* IDL_FORM_LEADERBOARD */
const wchar_t* IDL_FORM_LEADERBOARD = L"IDL_FORM_LEADERBOARD";
const wchar_t* IDC_LEADERBOARD_SCROLLPANEL = L"IDC_LEADERBOARD_SCROLLPANEL";
/* IDL_PANEL_LISTPANEL */
const wchar_t* IDL_PANEL_LISTPANEL = L"IDL_PANEL_LISTPANEL";
const wchar_t* IDC_LISTPANEL_IMG = L"IDC_LISTPANEL_IMG";
const wchar_t* IDC_LISTPANEL_LABEL_TITLE = L"IDC_LISTPANEL_LABEL_TITLE";
const wchar_t* IDC_LISTPANEL_LABEL_DESC = L"IDC_LISTPANEL_LABEL_DESC";
/* IDL_FORM_LEADERBOARDRANK */
const wchar_t* IDL_FORM_LEADERBOARDRANK = L"IDL_FORM_LEADERBOARDRANK";
const wchar_t* IDC_LEADERBOARDRANK_LIST_RANK = L"IDC_LEADERBOARDRANK_LIST_RANK";
/*const wchar_t* FOOTERITEM1; = L"FOOTERITEM1";*/
