#include "AppResourceId.h"
/* IDL_FORM_SEARCHFRIEND */
const wchar_t* IDL_FORM_SEARCHFRIEND = L"IDL_FORM_SEARCHFRIEND";
const wchar_t* IDC_SEARCHFRIEND_BUTTON_SEARCH = L"IDC_SEARCHFRIEND_BUTTON_SEARCH";
const wchar_t* IDC_SEARCHFRIEND_LIST_FRIEND = L"IDC_SEARCHFRIEND_LIST_FRIEND";
const wchar_t* IDC_SEARCHFRIEND_TEXTBOX_FRIEND = L"IDC_SEARCHFRIEND_TEXTBOX_FRIEND";
/* IDL_FORM */
const wchar_t* IDC_JOIN_GALLERY_EDIT = L"IDC_JOIN_GALLERY_EDIT";
const wchar_t* IDL_FORM = L"IDL_FORM";
const wchar_t* IDSCNT_MAIN_SCENE = L"IDSCNT_MAIN_SCENE";
const wchar_t* IDC_BUTTON_OK = L"IDC_BUTTON_OK";
/* IDL_FORM_LOGIN */
const wchar_t* IDL_FORM_LOGIN = L"IDL_FORM_LOGIN";
const wchar_t* IDC_LOGIN_TEXT_EMAILTITLE = L"IDC_LOGIN_TEXT_EMAILTITLE";
const wchar_t* IDC_LOGIN_TEXT_PWTITLE = L"IDC_LOGIN_TEXT_PWTITLE";
const wchar_t* IDC_LOGIN_EDITTEXT_EMAIL = L"IDC_LOGIN_EDITTEXT_EMAIL";
const wchar_t* IDC_LOGIN_EDITTEXT_PW = L"IDC_LOGIN_EDITTEXT_PW";
const wchar_t* IDC_LOGIN_BUTTON_JOIN = L"IDC_LOGIN_BUTTON_JOIN";
const wchar_t* IDC_LOGIN_BUTTON_SIGN = L"IDC_LOGIN_BUTTON_SIGN";
/* IDL_FORM_JOIN */
const wchar_t* IDL_FORM_JOIN = L"IDL_FORM_JOIN";
const wchar_t* IDC_JOIN_BUTTON_CANCEL = L"IDC_JOIN_BUTTON_CANCEL";
const wchar_t* IDC_JOIN_BUTTON_JOIN = L"IDC_JOIN_BUTTON_JOIN";
const wchar_t* IDC_JOIN_EDITTEXT_EMAIL = L"IDC_JOIN_EDITTEXT_EMAIL";
const wchar_t* IDC_JOIN_EDITTEXT_NAME = L"IDC_JOIN_EDITTEXT_NAME";
const wchar_t* IDC_JOIN_EDITTEXT_PW = L"IDC_JOIN_EDITTEXT_PW";
const wchar_t* IDC_JOIN_EDITTEXT_PWCONFIRM = L"IDC_JOIN_EDITTEXT_PWCONFIRM";
const wchar_t* IDC_JOIN_TEXT_EMAILTITLE = L"IDC_JOIN_TEXT_EMAILTITLE";
const wchar_t* IDC_JOIN_TEXT_NAMETITLE = L"IDC_JOIN_TEXT_NAMETITLE";
const wchar_t* IDC_JOIN_TEXT_PWCONFIRMTITLE = L"IDC_JOIN_TEXT_PWCONFIRMTITLE";
const wchar_t* IDC_JOIN_TEXT_PWTITLE = L"IDC_JOIN_TEXT_PWTITLE";
const wchar_t* IDC_JOIN_GALLERY_PROFILE = L"IDC_JOIN_GALLERY_PROFILE";
/* IDL_FORM_PLAYER */
const wchar_t* IDL_FORM_PLAYER = L"IDL_FORM_PLAYER";
const wchar_t* IDL_FORM_PLAYERFRIEND = L"IDL_FORM_PLAYERFRIEND";
const wchar_t* IDC_USER_PANEL_USER = L"IDC_USER_PANEL_USER";
const wchar_t* IDC_USER_LABEL_USERNAME = L"IDC_USER_LABEL_USERNAME";
const wchar_t* IDC_USER_LABEL_USERSCORETITLE = L"IDC_USER_LABEL_USERSCORETITLE";
const wchar_t* IDC_USER_LABEL_USERSCORE = L"IDC_USER_LABEL_USERSCORE";
const wchar_t* IDC_USER_IMG_USERIMG = L"IDC_USER_IMG_USERIMG";
const wchar_t* IDC_USER_BUTTON_USERFRIEND = L"IDC_USER_BUTTON_USERFRIEND";
const wchar_t* IDC_USER_SCROLLPANEL = L"IDC_USER_SCROLLPANEL";
const wchar_t* IDC_USER_PANEL_GAME = L"IDC_USER_PANEL_GAME";
const wchar_t* IDC_USER_LABEL_GAMETITLE = L"IDC_USER_LABEL_GAMETITLE";
const wchar_t* IDC_USER_LISTVIEW_GAME = L"IDC_USER_LISTVIEW_GAME";
const wchar_t* IDC_USER_PANEL_FRIEND = L"IDC_USER_PANEL_FRIEND";
const wchar_t* IDC_USER_LABEL_FRIENDTITLE = L"IDC_USER_LABEL_FRIENDTITLE";
const wchar_t* IDC_USER_LISTVIEW_FRIEND = L"IDC_USER_LISTVIEW_FRIEND";
const wchar_t* IDC_USER_BUTTON_SEARCHFRIEND = L"IDC_USER_BUTTON_SEARCHFRIEND";
/* IDL_FORM_GAME */
const wchar_t* IDL_FORM_GAME = L"IDL_FORM_GAME";
const wchar_t* IDC_GAME_PANEL_GAME = L"IDC_GAME_PANEL_GAME";
const wchar_t* IDC_GAME_IMG_GAMEIMG = L"IDC_GAME_IMG_GAMEIMG";
const wchar_t* IDC_GAME_LABEL_GAMENAME = L"IDC_GAME_LABEL_GAMENAME";
const wchar_t* IDC_GAME_LABEL_DEVELOPER = L"IDC_GAME_LABEL_DEVELOPER";
const wchar_t* IDC_GAME_BUTTON_DOWNLOAD = L"IDC_GAME_BUTTON_DOWNLOAD";
//
const wchar_t* IDC_GAME_SCROLLPANEL = L"IDC_GAME_SCROLLPANEL";
const wchar_t* IDC_GAME_PANEL_GAMEDETAIL = L"IDC_GAME_PANEL_GAMEDETAIL";
const wchar_t* IDC_GAME_PANEL_FUNCTION = L"IDC_GAME_PANEL_FUNCTION";
const wchar_t* IDC_GAME_BUTTON_LEADERBOARD = L"IDC_GAME_BUTTON_LEADERBOARD";
const wchar_t* IDC_GAME_BUTTON_ACHIEVEMENT = L"IDC_GAME_BUTTON_ACHIEVEMENT";
const wchar_t* IDC_GAME_LABEL_DESCRIPTIONTITLE = L"IDC_GAME_LABEL_DESCRIPTIONTITLE";
const wchar_t* IDC_GAME_LABEL_DESC = L"IDC_GAME_LABEL_DESC";
const wchar_t* IDC_GAME_PANEL_FRIEND = L"IDC_GAME_PANEL_FRIEND";
const wchar_t* IDC_GAME_LABEL_FRIENDTITLE = L"IDC_GAME_LABEL_FRIENDTITLE";
const wchar_t* IDC_GAME_LISTVIEW_FRIEND = L"IDC_GAME_LISTVIEW_FRIEND";
/* IDL_FORM_ACHIEVEMENT */
const wchar_t* IDL_FORM_ACHIEVEMENT = L"IDL_FORM_ACHIEVEMENT";
const wchar_t* IDC_ACHIEVEMENT_SCROLLPANEL = L"IDC_ACHIEVEMENT_SCROLLPANEL";
const wchar_t* IDC_ACHIEVEMENT_LABEL_TITLE = L"IDC_ACHIEVEMENT_LABEL_TITLE";
/* IDL_FORM_LEADERBOARD */
const wchar_t* IDL_FORM_LEADERBOARD = L"IDL_FORM_LEADERBOARD";
const wchar_t* IDC_LEADERBOARD_SCROLLPANEL = L"IDC_LEADERBOARD_SCROLLPANEL";
/* IDL_PANEL_LISTPANEL */
const wchar_t* IDL_PANEL_LISTPANEL = L"IDL_PANEL_LISTPANEL";
const wchar_t* IDC_LISTPANEL_IMG = L"IDC_LISTPANEL_IMG";
const wchar_t* IDC_LISTPANEL_LABEL_TITLE = L"IDC_LISTPANEL_LABEL_TITLE";
const wchar_t* IDC_LISTPANEL_LABEL_DESC = L"IDC_LISTPANEL_LABEL_DESC";
const wchar_t* IDC_LISTPANEL_LABEL_POINT = L"IDC_LISTPANEL_LABEL_POINT";
const wchar_t* IDC_LISTPANEL_GALLERY_COMPLETE = L"IDC_LISTPANEL_GALLERY_COMPLETE";
const wchar_t* IDC_LISTPANEL_OVERLAY = L"IDC_LISTPANEL_OVERLAY";
/* IDL_FORM_LEADERBOARDRANK */
const wchar_t* IDL_FORM_LEADERBOARDRANK = L"IDL_FORM_LEADERBOARDRANK";
const wchar_t* IDC_LEADERBOARDRANK_LIST_RANK = L"IDC_LEADERBOARDRANK_LIST_RANK";
/* IDL_CROPFORM */
const wchar_t* IDF_CROPFROM = L"IDF_CROPFROM";
/*const wchar_t* FOOTERITEM1; = L"FOOTERITEM1";*/
