#include "AppResourceId.h"
/* IDL_FORM_GAME */
const wchar_t* IDC_GAME_CARD1 = L"IDC_GAME_CARD1";
const wchar_t* IDC_GAME_CARD2 = L"IDC_GAME_CARD2";
const wchar_t* IDC_GAME_CARD3 = L"IDC_GAME_CARD3";
const wchar_t* IDC_GAME_CARD4 = L"IDC_GAME_CARD4";
const wchar_t* IDC_GAME_CARD5 = L"IDC_GAME_CARD5";
const wchar_t* IDC_GAME_CARD6 = L"IDC_GAME_CARD6";
const wchar_t* IDC_GAME_CARD7 = L"IDC_GAME_CARD7";
const wchar_t* IDC_GAME_CARD8 = L"IDC_GAME_CARD8";
const wchar_t* IDC_GAME_CARD9 = L"IDC_GAME_CARD9";
const wchar_t* IDC_GAME_CARD10 = L"IDC_GAME_CARD10";
const wchar_t* IDC_GAME_CARD11 = L"IDC_GAME_CARD11";
const wchar_t* IDC_GAME_CARD12 = L"IDC_GAME_CARD12";
const wchar_t* IDC_GAME_CARD13 = L"IDC_GAME_CARD13";
const wchar_t* IDC_GAME_CARD14 = L"IDC_GAME_CARD14";
const wchar_t* IDC_GAME_CARD15 = L"IDC_GAME_CARD15";
const wchar_t* IDC_GAME_CARD16 = L"IDC_GAME_CARD16";
const wchar_t* IDC_GAME_CARD17 = L"IDC_GAME_CARD17";
const wchar_t* IDC_GAME_CARD18 = L"IDC_GAME_CARD18";
const wchar_t* IDC_GAME_CARD19 = L"IDC_GAME_CARD19";
const wchar_t* IDC_GAME_CARD20 = L"IDC_GAME_CARD20";
const wchar_t* IDC_GAME_LABEL_COUNT = L"IDC_GAME_LABEL_COUNT";
const wchar_t* IDC_GAME_LABEL_MYTURN = L"IDC_GAME_LABEL_MYTURN";
const wchar_t* IDC_GAME_LABEL_OTHERTURN = L"IDC_GAME_LABEL_OTHERTURN";
const wchar_t* IDC_GAME_LABEL_SCORE = L"IDC_GAME_LABEL_SCORE";
const wchar_t* IDC_GAME_LABEL_SCORE2 = L"IDC_GAME_LABEL_SCORE2";
const wchar_t* IDC_GAME_LABEL_TIMER = L"IDC_GAME_LABEL_TIMER";
const wchar_t* IDC_LABEL1 = L"IDC_LABEL1";
const wchar_t* IDC_LABEL2 = L"IDC_LABEL2";
const wchar_t* IDC_MAIN_BUTTON_LOGIN = L"IDC_MAIN_BUTTON_LOGIN";
const wchar_t* IDL_FORM_GAME = L"IDL_FORM_GAME";
const wchar_t* IDL_FORM_GAME2 = L"IDL_FORM_GAME2";
const wchar_t* IDL_FORM_GAME3 = L"IDL_FORM_GAME3";
/* IDL_FORM_MODESELECT */
const wchar_t* IDC_MODE_BUTTON_MULTI = L"IDC_MODE_BUTTON_MULTI";
const wchar_t* IDC_MODE_BUTTON_SECONDS = L"IDC_MODE_BUTTON_SECONDS";
const wchar_t* IDC_MODE_BUTTON_TIME = L"IDC_MODE_BUTTON_TIME";
const wchar_t* IDL_FORM_MODESELECT = L"IDL_FORM_MODESELECT";
/* IDL_FORM */
const wchar_t* IDL_FORM = L"IDL_FORM";
const wchar_t* IDL_FORM2 = L"IDL_FORM2";
const wchar_t* IDL_FORM3 = L"IDL_FORM3";
const wchar_t* IDC_MAIN_BUTTON_PLAY = L"IDC_MAIN_BUTTON_PLAY";
const wchar_t* IDC_MAIN_BUTTON_LEADERBOARD = L"IDC_MAIN_BUTTON_LEADERBOARD";
const wchar_t* IDC_MAIN_BUTTON_ACHIEVEMENT = L"IDC_MAIN_BUTTON_ACHIEVEMENT";
/* SCENE */
const wchar_t* IDSCNT_MAIN_SCENE = L"IDSCNT_MAIN_SCENE";
const wchar_t* MainScene = L"MainScene";
